// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Devices = __t.object("Devices", {
  id: __t.u64(),
  shopId: __t.u64(),
  secret: __t.string(),
});
export type Devices = __Infer<typeof Devices>;

export const OrderItems = __t.object("OrderItems", {
  id: __t.u64(),
  orderId: __t.u64(),
  productId: __t.u64(),
  quantity: __t.u32(),
});
export type OrderItems = __Infer<typeof OrderItems>;

export const Orders = __t.object("Orders", {
  id: __t.u64(),
  shopId: __t.u64(),
  deviceId: __t.u64(),
  userId: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type Orders = __Infer<typeof Orders>;

export const Products = __t.object("Products", {
  id: __t.u64(),
  shopId: __t.u64(),
  name: __t.string(),
  price: __t.u64(),
});
export type Products = __Infer<typeof Products>;

export const Shops = __t.object("Shops", {
  id: __t.u64(),
  name: __t.string(),
  owner: __t.identity(),
});
export type Shops = __Infer<typeof Shops>;

