// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  deviceId: __t.u64(),
  userId: __t.string(),
  encryptedQr: __t.string(),
  productIds: __t.array(__t.u64()),
  quantities: __t.array(__t.u32()),
  paymentVerified: __t.bool(),
};
