// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddProductReducer from "../add_product_reducer";
import CreateShopReducer from "../create_shop_reducer";
import GetQueuePositionReducer from "../get_queue_position_reducer";
import RegisterDeviceReducer from "../register_device_reducer";
import UpdateOrderStatusReducer from "../update_order_status_reducer";
import VerifyAndPlaceOrderReducer from "../verify_and_place_order_reducer";

export type AddProductParams = __Infer<typeof AddProductReducer>;
export type CreateShopParams = __Infer<typeof CreateShopReducer>;
export type GetQueuePositionParams = __Infer<typeof GetQueuePositionReducer>;
export type RegisterDeviceParams = __Infer<typeof RegisterDeviceReducer>;
export type UpdateOrderStatusParams = __Infer<typeof UpdateOrderStatusReducer>;
export type VerifyAndPlaceOrderParams = __Infer<typeof VerifyAndPlaceOrderReducer>;

